### ISSUE TITLE
using the {{include.___}} variable on a background image

### ISSUE THREAD

**Issue by JuliaProkipcak** [JuliaProkipcak/ecommerce-pattern-library#3]
Hi,
My main banner is using a background image and I'm having trouble setting it up with the variable. Thomas told me I can't use the include variable in css and emailed me how I can use the css background image attribute in html so that I can add it. After I tried to implement this the image disappeared.. whoops. Let me know if you can figure out what I did wrong.
Thanks,
- Julia

@hannahdelaney

**Comment by HannahDelaney** [comment]
Hey!

I had a look at what Thomas suggested. As long as your config file is set up to indicate what the include is for, I'd hope it would work, might be a typing error somewhere? Are you able to commit and push the files for the main banner you're working on so I can see what things look like? It's not been committed in the past week-ish, so I don't see the background img element in your html anywhere.

Hannah :)

**Comment by JuliaProkipcak** [comment]
Hi,
Sorry about that, I had been forgetting to commit. I'm currently working on the include variable for the other patterns I have so there are other elements getting messed up but I haven't been able to figure out the main banner yet. I'm sure its a small error in typing or something but I can't seem to find it

**Comment by HannahDelaney** [comment]
Yeah, the includes can go several layers deep in different files sometimes and be a bit confusing. I had this as well!

I've noticed that with yours, the string you've used in your config file isn't a full background-image source tag. You have "banner-2.jpg" as the example text to put in place of the include tag, but in your html you've written the include as [style="background-image:url({{include.img}})"]. The include tag replaces everything in place of where the double curly braces start and end, so you'll need to put a full link through the files of where the image is, not just the name of it.

Try writing something like:
"      - name: 'banner'
        type: 'string'
        example: '/images/banners/banner-2.jpg'
"
in your config, rather than just:

"      - name: 'banner'
        type: 'string'
        example: 'banner-2.jpg'
"

I hope that makes sense!
Hannah :)
